### ISSUE TITLE
Ошибка в базовой цене Набивки для тюфяков

### ISSUE THREAD

**Issue by SanyaSol** [symphograph/dllib#26]
Базовая цена набивки для тюфяков из ПСО в Ост-Терру по базе данных сайта 29г 88с 56м, из-за чего этот пак находится высоко в списке по выгоде на 1 ОР, я отвёз этот пак ради проверки (сомневался, что пак имеет такую цену для мирной территории), вышло, что тут ошибка, базовая цена пака указана на скриншоте
![2b98a-clip-40kb](https://user-images.githubusercontent.com/84777740/119486117-33dfaa80-bd58-11eb-95e5-5cdfc38a6739.jpg)

**Comment by symphograph** [comment]
Пасип! Исправлено.=)
